name: build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          - target: universal-apple-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin

      - name: Build Tauri app
        run: pnpm tauri build --target ${{ matrix.target }}

      - name: Upload dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: Powerflow-dmg
          path: |
            target/universal-apple-darwin/release/bundle/dmg/*.dmg
            **/bundle/dmg/*.dmg
          if-no-files-found: error
